language: python
python:
- '3.6'
before_install:
- sudo apt-get install graphviz
install:
- pip install -r requirements.txt --quiet
- pip install mkdocs
- pip install mkdocs-material
script:
- pytest tests --cov=autokeras
- sh docs.sh
after_success:
- pip install python-coveralls && coveralls
