language: python
python:
- '3.6'
before_install:
- sudo apt-get install graphviz
install:
- pip install -r requirements.txt --quiet
- pip install mkdocs
- pip install mkdocs-material
script:
- pytest tests --cov=autokeras
- sh docs.sh
after_success:
- pip install python-coveralls && coveralls
deploy:
- provider: pypi
  user: "jeziellago"
  password:
    secure: $REPO_KEY
    tags: true
    repo: jeziellago/autokeras

- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: docs/
  target-branch: gh-pages
  on:
    branch: master
